openapi: 3.0.0
info:
  contact:
    email: m@m.com
    name: Swagger API Team
    url: https://swagger.io
  description: "relearn"
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Swagger relearn
  version: 1.0.0
servers:
  - description: "Optional server description, e.g. Main (production) server"
    url: localhost:8080
tags:
  - description: Everything about relern
    externalDocs:
      description: Find out more
      url: http://swagger.io
    name: relern
paths:
  /questions:
    get:
      operationId: listQuestions
      parameters:
        - description: How many items to return at one time (max 100)
          explode: true
          in: query
          name: limit
          required: false
          schema:
            format: int64
            type: integer
          style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Question"
                type: array
          description: List of all the users
      summary: List all questions
      tags:
        - relern
  /answers:
    post:
      operationId: createAnswer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Answer"
          description: Created answer
      summary: Create a new answer
      tags:
        - relern
  /health:
    get:
      operationId: health
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Health"
          description: Health check
      summary: Health check
      tags:
        - relern
components:
  schemas:
    Answer:
      example:
        valid: true
        questionId: 0
        user_id: 6
        org_id: 1
        created_at: 2000-01-23T04:56:07.000+00:00
      properties:
        questionId:
          format: int64
          type: integer
        valid:
          type: boolean
        created_at:
          format: date-time
          type: string
        user_id:
          format: int64
          type: integer
        org_id:
          format: int64
          type: integer
      required:
        - questionId
      type: object
    Question:
      example:
        reference:
          - reference
          - reference
        number: 0
        question: question
        level: level
        correct_response: correct_response
        wrong_response: wrong_response
        hint: hint
        correct_answer: 6
        answers:
          - answers
          - answers
        tag: tag
        point_reward: 1
        tags:
          - tags
          - tags
      properties:
        level:
          type: string
        tag:
          type: string
        number:
          format: int64
          type: integer
        question:
          type: string
        correct_answer:
          format: int64
          type: integer
        answers:
          items:
            type: string
          type: array
        point_reward:
          format: int64
          type: integer
        tags:
          items:
            type: string
          type: array
        hint:
          type: string
        reference:
          items:
            type: string
          type: array
        correct_response:
          type: string
        wrong_response:
          type: string
      required:
        - answers
        - correct_answer
        - hint
        - level
        - point_reward
        - question
        - tag
      type: object
    Health:
      example:
        status: status
      properties:
        status:
          type: string
      required:
        - status
      type: object
