/*
 * Swagger relearn
 *
 * relearn
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: m@m.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Health {
    #[serde(rename = "status")]
    pub status: String,
}

impl Health {
    pub fn new(status: String) -> Health {
        Health { status }
    }
}
