/*
 * Swagger relearn
 *
 * relearn
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: m@m.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Question {
    #[serde(rename = "level")]
    pub level: String,
    #[serde(rename = "tag")]
    pub tag: String,
    #[serde(rename = "number", skip_serializing_if = "Option::is_none")]
    pub number: Option<i64>,
    #[serde(rename = "question")]
    pub question: String,
    #[serde(rename = "correct_answer")]
    pub correct_answer: i64,
    #[serde(rename = "answers")]
    pub answers: Vec<String>,
    #[serde(rename = "point_reward")]
    pub point_reward: i64,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "hint")]
    pub hint: String,
    #[serde(rename = "reference", skip_serializing_if = "Option::is_none")]
    pub reference: Option<Vec<String>>,
    #[serde(rename = "correct_response", skip_serializing_if = "Option::is_none")]
    pub correct_response: Option<String>,
    #[serde(rename = "wrong_response", skip_serializing_if = "Option::is_none")]
    pub wrong_response: Option<String>,
}

impl Question {
    pub fn new(
        level: String,
        tag: String,
        question: String,
        correct_answer: i64,
        answers: Vec<String>,
        point_reward: i64,
        hint: String,
    ) -> Question {
        Question {
            level,
            tag,
            number: None,
            question,
            correct_answer,
            answers,
            point_reward,
            tags: None,
            hint,
            reference: None,
            correct_response: None,
            wrong_response: None,
        }
    }
}
